# Generated by Django 4.0.2 on 2022-02-02 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('birth_date', models.PositiveSmallIntegerField()),
                ('bio', models.CharField(max_length=150)),
                ('prof_pic', models.URLField(blank=True)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
                ('followers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_followers', to='users.account')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_followings', to='users.account')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
