# Generated by Django 4.0.2 on 2022-02-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='bio',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='account',
            name='birth_date',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
