# Generated by Django 4.0.2 on 2022-02-02 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_account_bio_alter_account_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='followers',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_followers', to='users.account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='following',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_followings', to='users.account'),
        ),
    ]
